// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Mutual_ExclusionClient is the client API for Mutual_Exclusion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Mutual_ExclusionClient interface {
	Request(ctx context.Context, in *AdminRequest, opts ...grpc.CallOption) (*Reply, error)
	SendReply(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*Empty, error)
}

type mutual_ExclusionClient struct {
	cc grpc.ClientConnInterface
}

func NewMutual_ExclusionClient(cc grpc.ClientConnInterface) Mutual_ExclusionClient {
	return &mutual_ExclusionClient{cc}
}

func (c *mutual_ExclusionClient) Request(ctx context.Context, in *AdminRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/Mutual_Exclusion/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mutual_ExclusionClient) SendReply(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Mutual_Exclusion/SendReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Mutual_ExclusionServer is the server API for Mutual_Exclusion service.
// All implementations must embed UnimplementedMutual_ExclusionServer
// for forward compatibility
type Mutual_ExclusionServer interface {
	Request(context.Context, *AdminRequest) (*Reply, error)
	SendReply(context.Context, *Reply) (*Empty, error)
	mustEmbedUnimplementedMutual_ExclusionServer()
}

// UnimplementedMutual_ExclusionServer must be embedded to have forward compatible implementations.
type UnimplementedMutual_ExclusionServer struct {
}

func (UnimplementedMutual_ExclusionServer) Request(context.Context, *AdminRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedMutual_ExclusionServer) SendReply(context.Context, *Reply) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendReply not implemented")
}
func (UnimplementedMutual_ExclusionServer) mustEmbedUnimplementedMutual_ExclusionServer() {}

// UnsafeMutual_ExclusionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Mutual_ExclusionServer will
// result in compilation errors.
type UnsafeMutual_ExclusionServer interface {
	mustEmbedUnimplementedMutual_ExclusionServer()
}

func RegisterMutual_ExclusionServer(s grpc.ServiceRegistrar, srv Mutual_ExclusionServer) {
	s.RegisterService(&Mutual_Exclusion_ServiceDesc, srv)
}

func _Mutual_Exclusion_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Mutual_ExclusionServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Mutual_Exclusion/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Mutual_ExclusionServer).Request(ctx, req.(*AdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mutual_Exclusion_SendReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Mutual_ExclusionServer).SendReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Mutual_Exclusion/SendReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Mutual_ExclusionServer).SendReply(ctx, req.(*Reply))
	}
	return interceptor(ctx, in, info, handler)
}

// Mutual_Exclusion_ServiceDesc is the grpc.ServiceDesc for Mutual_Exclusion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mutual_Exclusion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Mutual_Exclusion",
	HandlerType: (*Mutual_ExclusionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _Mutual_Exclusion_Request_Handler,
		},
		{
			MethodName: "SendReply",
			Handler:    _Mutual_Exclusion_SendReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
